### PR TITLE
Removal of the blank space above the red line

### PR DESCRIPTION
**Pull request by Sandra97**
I'm most probably going to break things or do them wrong...

### CODE REVIEW

**Comment by mbabker** [comment]
Well, you’re right in that you’re breaking the Bootstrap helper class 😝

The homepage template (`resources/views/homepage.blade.php`) should have the class removed from the list instead of this change.  But, IIRC, that causes the line to butt up against the content and I purposefully was trying to avoid that.

**Comment by Sandra97** [comment]
You told me to make PR. I listened. You knew I'll give you headaches, even more on a system I don't know at all.  
I'll check better.

**Comment by Sandra97** [comment]
Removing the class in the file looks good to me. Then, it just depend  if it's what you want or not (and you have better eyes than me)
index

**Comment by mbabker** [comment]
That’s the butting up on content thing I didn’t like.  If the line were only on the homepage I could live with it but since it’s everywhere personally I think it’s better if it consistently has padding between the end of the main body and the footer.

**Comment by mbabker** [comment]
The other viable option is to remove the line on the homepage.  But then the copyright looks kind of out of place floating off on its own.

**Comment by Sandra97** [comment]
I would not remove it on the hompeage, I like having a separation with the footer elements. 
I presume I can close this. I'll try to do other things (and break more things)

**Comment by mbabker** [comment]
Yeah, close for now.

**Pull request closed without merging**
